// Credit: https://github.com/nova-wallet/nova-utils/blob/master/dapps/dapps_dev.json

import { PredefinedDApps } from 'types/browser';
import i18n from 'utils/i18n/i18n';

export const DAppIconMap: Record<string, string> = {
  'kintsugi.interlay.io': 'https://kintsugi.interlay.io/kintsugi/apple-touch-icon.png',
  'kanaria.rmrk.app': 'https://rmrk-unrestricted.mypinata.cloud/ipfs/QmSkVkPiMsr1Ryu7122KHoAHqsCrgQCWthNniykLKqbA5H',
  'distribution.acala.network': 'https://avatars.githubusercontent.com/u/54881907?s=200&v=4',
  'www.xdao.app': 'https://moonbeam.network/wp-content/uploads/2022/03/xDAO.png',
  'crowdloan.interlay.io': 'https://assets.coingecko.com/coins/images/26180/small/Interlay-Coinbase-2.png',
  'ace.web3go.xyz': 'https://ace.web3go.xyz/favicon.ico',
  'www.avault.network': 'https://www.avault.network/logo.png',
  'astr.domains': 'https://astr.domains/logo/logo_cic.png',
  'tfalpha.xyz': 'https://tfalpha.xyz/img/tfa-logo.png',
};

export const DAppTitleMap: Record<string, string> = {
  'singular.app': 'Singular: Kusama-native NFTs #RMRK #NFT',
  'singular.rmrk.app': 'Singular: Kusama-native NFTs #RMRK #NFT',
  'kanaria.rmrk.app': 'KANARIA',
  'bifrost.app': 'Bifrost',
  'portal.astar.network': 'Astar Portal - Astar & Shiden Network',
  'app.subsocial.network': 'Subsocial - Decentralized social network on Polkadot & IPFS',
  'polkadot.js.org': 'Polkadot/Substrate Portal',
  'kodadot.xyz': 'KodaDot - Kusama NFT Market Explorer',
  'dotmarketcap.com': 'DotMarketCap',
  'app.parallel.fi': 'Parallel Finance',
  'polkadot.polkassembly.io': 'Polkassembly',
  'ksmcrowdloan.bit.country': 'Crowdloan - Bit.Country Pioneer Network',
  'crowdloan.parallel.fi': 'Parallel Finance',
  'kintsugi.interlay.io': 'Kintsugi',
  'distribution.acala.network': 'Acala Distribution Query',
  'dapp.robonomics.network': 'Dapp Robonomics network',
  'apps.moonbeam.network': 'Moonbeam Network Apps',
  'app.solarflare.io': 'Solarflare',
  'app.solarbeam.io': 'Solarbeam',
  'app.beamswap.io': 'Beamswap',
  'app.stellaswap.com': 'StellaSwap - Leading Moonbeam DEX & DeFi Gateway',
  'app.impossible.finance': 'Impossible Finance',
  'clover.huckleberry.finance': 'Huckleberry',
  'moonriver.huckleberry.finance': 'moonriver.huckleberry.finance',
  'singular-rmrk2-dev.vercel.app': 'Singular: Kusama-native NFTs #RMRK #NFT',
  'centrifuge.io': 'Centrifuge: Real World DeFi',
  'dappradar.com': 'DappRadar - The World’s Dapp Store',
  'tofunft.com': 'tofuNFT.com',
  'app.arthswap.org': 'ArthSwap',
  'cbridge.celer.network': 'cBridge',
  'www.xdao.app': 'XDAO – MultiChain DAO Ecosystem',
  'crowdloan.interlay.io': 'Interlay',
  'kusama.lido.fi': 'Lido',
  'polkadot.lido.fi': 'Lido',
  'moonwell.fi': 'Moonwell Apollo',
  'apps.litentry.com': 'Litmus Network',
  'apps.darwinia.network': 'Darwinia',
  'polkawatch.app': 'Polkawatch',
  'damnedpiratessociety.io': 'Damned Pirates Society',
  'staking.polkadot.network': 'Polkadot Staking Dashboard',
  'marketplace.moonsama.com': 'Moonsama',
  'game.evrloot.com': 'Join the Adventure -- evrloot',
  'www.dtmb.xyz': 'DOWNTOWN MOONBEAM',
  'portal.evolution.land': 'Evolution Land',
  'app.basilisk.cloud': 'Basilisk',
  'moonbeam.curve.fi': 'Curve.fi',
  'app.gmordie.com': 'GM - Say it back!',
  'pioneer.bit.country': 'Bit Country - Metaverses made of 1 and 0 bits',
  'app.zeitgeist.pm': 'The Zeitgeist Prediction Markets App',
  'ace.web3go.xyz': 'ACE',
  'mf-raffle-game.web.app': 'Moonfit - Raffle game',
  'dev-event.moonfit.xyz': 'Moonfit - Raffle game',
  'www.dotinsights.xyz': 'dotinsights | Polkadot & Kusama Ecosystem Map',
  'app.phala.network': 'Phala App',
  'dex.zenlink.pro': 'Zenlink',
  'www.avault.network': 'Avault',
  'panoramaswap.app': 'Panorama Swap',
  'app.taigaprotocol.io': 'TAIGA',
  'astr.domains': 'Astar Web3 Domains (.astr) - Your Perfect NFT Domains',
  'event.tfalpha.xyz': 'Raffle & Claim Rewards',
  'tfalpha.xyz': 'Utopia & TF Alpha',
  'moons.money': 'Moon Web3 identity',
  'www.subsquare.io': 'SubSquare - Empower the governance of substrate.',
  'mint.azeropunks.com': 'AzeroPunks',
  'app.polkasafe.xyz': 'Polkasafe',
  'www.bananaswap.app': 'Bananaswap',
  'app.bounce.finance': 'Bounce',
  'www.hashkey.id': 'Bounce',
  'bluez.app': 'Bluez',
  'enterthemandala.app': 'Mandala',
  'www.mangata.finance': 'Mangata - The DEX of the future',
  'app.dam.finance': 'DAM',
  'apps.acala.network': 'Acala Platform',
  'app.equilibrium.io': 'Equilibrium',
  'www.gear-tech.io': 'Gear Technologies | Crypto. Smarter.',
  'apps.karura.network': 'Karura Platform',
  'app.moonfit.xyz': 'MoonFit - Web3 & NFT Lifestyle App',
  'app.sirius.finance': 'Sirius Finance',
  'sub.id': 'Sub ID: Substrate Addresses, Balances, Crowdloans and NFTs',
  'polkaverse.com': "PolkaVerse – Polkadot's Premier Social Network",
  'polkaswap.io': 'Swap - Polkaswap',
  'app.privadex.xyz': 'PrivaDEX',
  'notifi.network': 'Notifi',
  'skybreach.app': 'Kanaria Skybreach',
  'pods.spacers.app': 'Spacers NFT Pods Sale',
  'list.yieldbay.io': 'YieldBay',
  'app.fidi.tech': 'FiDi',
  'www.braindex.io': 'Braindex | Smart Dex Aggregator',
  'app.uniswap.org': 'Swap - Curve',
  'curve.fi': 'Aave - Open Source Liquidity Protocol',
  'app.aave.com': 'Aave - Open Source Liquidity Protocol',
  'lido.fi': 'Liquid Staking for Digital Tokens',
  'blur.io': 'Blur: NFT Marketplace for Pro Traders',
  'app.1inch.io': '1inch - DeFi / DEX aggregator on Ethereum, Binance Smart Chain, Optimism, Polygon, Arbitrum',
  'chainlist.org': 'Chainlist',
  'app.multichain.org': 'Multichain - Cross Chain Router Protocol',
  'www.portalbridge.com': 'Wormhole Bridge',
  'verse.bitcoin.com': 'Verse DEX',
};

export const predefinedDApps: PredefinedDApps = {
  categories: () => [
    {
      name: i18n.browser.defi,
      id: 'defi',
      theme: 'cyan',
    },
    {
      name: i18n.browser.EVM,
      id: 'evm',
      theme: 'magenta',
    },
    {
      name: i18n.browser.community,
      id: 'community',
      theme: 'volcano',
    },
    {
      name: i18n.browser.utilities,
      id: 'utilities',
      theme: 'orange',
    },
    {
      name: i18n.browser.crowdloans,
      id: 'crowdloans',
      theme: 'blue',
    },
    {
      name: i18n.browser.staking,
      id: 'staking',
      theme: 'geekblue',
    },
    {
      name: i18n.browser.test,
      id: 'test',
      theme: 'red',
    },
    {
      name: i18n.browser.data,
      id: 'data',
      theme: 'green',
    },
  ],
  dapps: [
    {
      name: '1inch - DeFi / DEX aggregator on Ethereum, Binance Smart Chain, Optimism, Polygon, Arbitrum',
      icon: 'https://app.1inch.io/assets/favicon/apple-touch-icon.png',
      id: 'app.1inch.io',
      url: 'https://app.1inch.io/',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: false,
    },
    {
      name: 'Chainlist',
      icon: 'https://chainlist.org/favicon.ico',
      id: 'chainlist.org',
      url: 'https://chainlist.org/',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: false,
    },
    {
      name: 'Mandala',
      icon: 'https://enterthemandala.app/SriChakraRainbow.png',
      id: 'enterthemandala.app',
      url: 'https://enterthemandala.app/HomePage',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: false,
    },
    {
      name: 'Raffle & Claim Rewards',
      icon: 'https://event.tfalpha.xyz/logo-32x32.ico',
      id: 'event.tfalpha.xyz',
      url: 'https://event.tfalpha.xyz/',
      categories: ['community'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: true,
    },
    {
      name: 'InkWhale.net - Staking and Yield Farming Platform on Aleph Zero',
      icon: 'https://www.inkwhale.net/apple-touch-icon.png',
      id: 'inkwhale.net',
      url: 'https://inkwhale.net',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: false,
    },
    {
      name: 'a0.inkwhale.net - Staking and Yield Farming Platform on Aleph Zero',
      icon: 'https://www.inkwhale.net/apple-touch-icon.png',
      id: 'a0.inkwhale.net',
      url: 'https://a0.inkwhale.net',
      categories: ['defi'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: false,
    },
    {
      name: 'Kusama Lido',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/LIDO_KSM.svg',
      id: 'kusama.lido.fi',
      url: 'https://kusama.lido.fi/',
      categories: ['staking', 'evm'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: true,
    },
    {
      name: 'YieldBay',
      icon: 'https://list.yieldbay.io/favicon/favicon.ico',
      id: 'list.yieldbay.io',
      url: 'https://list.yieldbay.io/',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: false,
    },
    {
      name: 'Moon Web3 identity',
      icon: 'https://moons.money/logo/logo.png?=2',
      id: 'moons.money',
      url: 'https://moons.money/app',
      categories: ['evm'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: true,
    },
    {
      name: 'Moonwell Apollo',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/dapps/color/Moonwell.svg',
      id: 'moonwell.fi/apollo/MOVR',
      url: 'https://moonwell.fi/apollo/MOVR',
      categories: ['defi', 'evm'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: true,
    },
    {
      name: 'Verse DEX | Bitcoin.comu00e2u20acu2122s official decentralized exchange',
      icon: 'https://verse.bitcoin.com/images/favicon.png',
      id: 'verse.bitcoin.com',
      url: 'https://verse.bitcoin.com/#/',
      categories: ['defi'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: false,
    },
    {
      name: 'HashKey DID',
      icon: 'https://www.hashkey.id/favicon.ico',
      id: 'www.hashkey.id',
      url: 'https://www.hashkey.id/home',
      categories: ['defi'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: false,
    },
    {
      name: 'Portal Token Bridge',
      icon: 'https://www.portalbridge.com/favicon.ico',
      id: 'www.portalbridge.com',
      url: 'https://www.portalbridge.com/',
      categories: ['defi'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: false,
    },
    {
      name: 'Subsquare',
      icon: 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/color/SubSquare.svg',
      id: 'www.subsquare.io',
      url: 'https://www.subsquare.io/',
      categories: ['community'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: false,
    },
    {
      name: 'HEAL-Ⅲ | Health to Earn',
      icon: 'https://heal3.com/favicon.svg',
      id: 'www.heal3.com',
      url: 'https://heal3.com',
      categories: ['defi', 'evm'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: true,
    },
    {
      name: 'Birdeye',
      icon: 'https://birdeye.so/logo.png',
      id: 'www.birdeye.so',
      url: 'https://birdeye.so',
      categories: ['defi', 'evm'],
      isSupportSubstrateAccount: false,
      isSupportEthereumAccount: true,
    },
    {
      name: 'AZERO.ID – Domain Service on Aleph Zero',
      icon: 'https://azero.id/favicon.ico',
      id: 'www.azero.id',
      url: 'https://azero.id',
      categories: ['defi', 'substrate'],
      isSupportSubstrateAccount: true,
      isSupportEthereumAccount: false,
    },
  ],
};
